// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycuayrdohvaafeovfmxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljdWF5cmRvaHZhYWZlb3ZmbXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyODA3ODcsImV4cCI6MjA3MDg1Njc4N30.SODGxbCs4hkwZq6h-htNAobVMJoMZkVa02fE7wRl0NU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});